---
title: "Cyclist Bike-Share"
author: "Veronica"
date: "2023-07-16"
output: html_document
---
### Load packages
```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(dplyr)
```
```{r}
### download files and give a name

file_202206 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202206-divvy-tripdata.csv")
file_202207 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202207-divvy-tripdata.csv")
file_202208 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202208-divvy-tripdata.csv")
file_202209 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202209-divvy-publictripdata.csv")
file_202210 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202210-divvy-tripdata.csv")
file_202211 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202211-divvy-tripdata.csv")
file_202212 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202212-divvy-tripdata.csv")
file_202301 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202301-divvy-tripdata.csv")
file_202302 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202212-divvy-tripdata.csv")
file_202303 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202303-divvy-tripdata.csv")
file_202304 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202304-divvy-tripdata.csv")
file_202305 <- read_csv("Downloads/Cyclistic_Case_Study_Spreadsheets/Cyclistic Capstone Project/202305-divvy-tripdata.csv")
```
```{r}
### View the column names and compare 

colnames(file_202206)
colnames(file_202207)
colnames(file_202208)
colnames(file_202209)
colnames(file_202210)
colnames(file_202211)
colnames(file_202212)
colnames(file_202301)
colnames(file_202302)
colnames(file_202303)
colnames(file_202304)
colnames(file_202305)


```
```{r}
### View the structure of the files

str(file_202206)
str(file_202207)
str(file_202208)
str(file_202209)
str(file_202210)
str(file_202211)
str(file_202212)
str(file_202301)
str(file_202302)
str(file_202303)
str(file_202304)
str(file_202305)

```
```{r}
### Change station_id into an integer 

file_202206$start_station_id <- as.integer(file_202206$start_station_id)
file_202207$start_station_id <- as.integer(file_202207$start_station_id)
file_202208$start_station_id <- as.integer(file_202208$start_station_id)
file_202209$start_station_id <- as.integer(file_202209$start_station_id)
file_202210$start_station_id <- as.integer(file_202210$start_station_id)
file_202211$start_station_id <- as.integer(file_202211$start_station_id)
file_202212$start_station_id <- as.integer(file_202212$start_station_id)
file_202301$start_station_id <- as.integer(file_202301$start_station_id)
file_202302$start_station_id <- as.integer(file_202302$start_station_id)
file_202303$start_station_id <- as.integer(file_202303$start_station_id)
file_202304$start_station_id <- as.integer(file_202304$start_station_id)
file_202305$start_station_id <- as.integer(file_202305$start_station_id)
```
```{r}
### Combine all data sets into one

all_trips <- bind_rows(file_202206,file_202207,file_202208,file_202209,file_202210,file_202211,file_202212,file_202301,file_202302,file_202303,file_202304,file_202305)
```
```{r}
### Adding columns for date, month, day, year, day_of_week

all_trips$date <- as.Date(all_trips$started_at)
all_trips$month <- format(as.Date(all_trips$date), "%B")
all_trips$day <- format(as.Date(all_trips$date), "%d")
all_trips$year <- format(as.Date(all_trips$date), "%Y")
all_trips$day_of_week <- weekdays(all_trips$date)
all_trips$ride_length <- difftime(all_trips$ended_at,all_trips$started_at)
```
```{r}

### Check the new columns

colnames(all_trips)
nrow(all_trips)
dim(all_trips)
head(all_trips)
str(all_trips)
summary(all_trips)
```
```{r}

### Check data for any duplicates 

unique(all_trips$member_casual)
unique(all_trips$rideable_type)
is.factor(all_trips$ride_length)
all_trips$ride_length <- as.numeric(as.character(all_trips$ride_length))
is.numeric(all_trips$ride_length)

```
```{r}

### Make a new data set and viewing the summary

all_trips_v2 <- all_trips[!(all_trips$start_station_name=="HQ QR"|all_trips$ride_length<0),]
mean(all_trips_v2$ride_length)
median(all_trips_v2$ride_length)
max(all_trips_v2ride_length)
min(all_trips_v2$ride_length)
summary(all_trips_v2$ride_length)
```
```{r}

### Aggregate to analyze the data and add a new column for day_of_week

aggregate(all_trips_v2$ride_length~all_trips_v2$member_casual,FUN = mean)
aggregate(all_trips_v2$ride_length~all_trips_v2$member_casual,FUN = median)
aggregate(all_trips_v2$ride_length~all_trips_v2$member_casual,FUN = max)
aggregate(all_trips_v2$ride_length~all_trips_v2$member_casual,FUN = min)
aggregate(all_trips_v2$ride_length~all_trips_v2$member_casual+all_trips_v2$day_of_week,FUN=mean)
all_trips_v2$day_of_week <-ordered(all_trips_v2$day_of_week,levels=c("Sunday","Monday","Tuesday","Wednesday","Thursay","Friday","Saturday"))
aggregate(all_trips_v2$ride_length~all_trips_v2$member_casual+all_trips_v2$day_of_week,FUN=mean)
```
```{r}
### Analyze all_trips_v2 by type and weekday

all_trips_v2 %>% 
  mutate(weekday=wday(started_at,label=TRUE)) %>% 
  group_by(member_casual,weekday) %>% 
  summarise(number_of_rides=n(),average_duration=mean(ride_length)) %>% 
  arrange(member_casual,weekday)


```
```{r}
### Visualize the number of rides by customer type and average duration

all_trips_v2 %>% 
  mutate(weekday=wday(started_at,label=TRUE)) %>% 
  group_by(member_casual,weekday) %>% 
  summarise(number_of_rides=n(),average_duration=mean(ride_length)) %>% 
  arrange(member_casual,weekday) %>% 
  ggplot(aes(x=weekday,y=number_of_rides,fill=member_casual))+
  geom_col(position = "dodge")


```
```{r}
counts <- aggregate(all_trips_v2$ride_length~all_trips_v2$member_casual+all_trips_v2$day_of_week,FUN=mean)
```
```{r}
### Make a new column for the season 

all_trips_v3 <- all_trips_v3 %>% mutate(season=recode(month,
                                                    December="Winter",
                                                    January="Winter",
                                                    Febuary="Spring",
                                                    March="Spring",
                                                    April="Spring",
                                                    May="Summer",
                                                    June="Summer",
                                                    July="Summer",
                                                    August="Fall",
                                                    September="Fall",
                                                    October="Fall",
                                                    November="Winter"))


```
```{r}
### Adding a column for the time of day

head(all_trips_v2)
all_trips_v2$ride_length_min <- round(as.numeric(difftime(all_trips_v2$ended_at, all_trips_v2$started_at, units = "mins")), 2)
class(all_trips_v2$ride_length_min)
all_trips_v2$hour <-lubridate::hour(all_trips_v2$started_at)
all_trips_v2 <- all_trips_v2 %>% mutate(time_of_day = case_when(
                        hour >= 6 & hour < 9 ~ "Early Morning",
                        hour >= 9 & hour < 12 ~ "Mid Morning",
                        hour >= 12 & hour < 18  ~ "Afternoon",
                        hour >= 18 & hour <= 23  ~ "Evening",
                        hour >= 0 & hour < 3  ~ "Early Night",
                        hour >= 3 & hour < 6  ~ "Late Night"))
```
```{r}
### Make a new column start_lat, start_lng, end_lat,end_lng rounded 

all_trips_v2 <- all_trips_v2 %>% 
  mutate(start_lat_round = round(start_lat, digits = 2),
        start_lng_round = round(start_lng, digits = 2),
        end_lat_round = round(end_lat, digits = 2),
        end_lng_round = round(end_lng, digits = 2))
### Remove missing data
all_trips_v2 <- all_trips_v2 %>% 
  group_by(end_lat_round, end_lng_round) %>% 
  tidyr::fill(end_station_name, .direction = "downup") %>% 
  ungroup()
all_trips_v2 <- all_trips_v2 %>% 
  group_by(start_lat_round,start_lng_round) %>% 
  tidyr::fill(start_station_name,.direction = "downup") %>% 
  ungroup
all_trips_v2 <- all_trips_v2 %>% 
  group_by(start_station_name) %>% 
  tidyr::fill(start_station_id, .direction = "downup") %>% 
  ungroup()
all_trips_v2 <- all_trips_v2 %>% 
  group_by(end_station_name) %>% 
  tidyr::fill(end_station_id, .direction = "downup") %>% 
  ungroup()


```
```{r}
### Now check missing values by column

colSums(is.na(all_trips_v2))
all_trips_v2 %>% filter(is.na(end_lat)) %>% 
  count(end_station_name, end_station_id, end_lat, end_lng, rideable_type)
all_trips_v2 %>% filter(is.na(start_station_name)) %>% 
  count(start_station_name, start_station_id, start_lat, start_lng, rideable_type)
all_trips_v2 %>% filter(is.na(end_station_name)) %>% 
  count(end_station_name, end_station_id, end_lat, end_lng, rideable_type)

```
```{r}
### Create a new dataset and remove tested drives

all_trips_v3 <- select(all_trips_v2, c(1,2,5, 6:16, 13:16, 18:22))

all_trips_v3 <- all_trips_v3 %>% 
  filter(ride_length_min >= 1 & ride_length_min <= 1440)
all_trips_v3 <- all_trips_v3 %>%
  filter(!is.na(end_lat) & !is.na(end_lng))
all_trips_v3 <- all_trips_v3 %>% 
  filter(!start_station_id %in% c("DIVVY 001", "DIVVY 001 - Warehouse test station", "Hubbard Bike-checking (LBS-WH-TEST)", "Pawel Bialowas - Test- PBSC charging station", "DIVVY CASSETTE REPAIR MOBILE STATION", "2059 Hastings Warehouse Station", "Hastings WH 2", "Throop/Hastings Mobile Station"))

all_trips_v3 <- all_trips_v3 %>%
  filter(!end_station_id %in% c("DIVVY 001", "DIVVY 001 - Warehouse test station", "Hubbard Bike-checking (LBS-WH-TEST)", "Pawel Bialowas - Test- PBSC charging station", "DIVVY CASSETTE REPAIR MOBILE STATION", "2059 Hastings Warehouse Station", "Hastings WH 2", "Throop/Hastings Mobile Station"))


```
```{r}
### Confirm ride length removal

sum(all_trips_v3$ride_length_min>1440)
sum(all_trips_v3$ride_length_min<1)
all_trips_v3 %>% filter(end_station_id %in% c("DIVVY 001", "DIVVY 001 - Warehouse test station", "Hubbard Bike-checking (LBS-WH-TEST)", "Pawel Bialowas - Test- PBSC charging station", "DIVVY CASSETTE REPAIR MOBILE STATION", "2059 Hastings Warehouse Station", "Hastings WH 2", "Throop/Hastings Mobile Station")) %>% 
  count(end_station_id)
all_trips_v3 %>% filter(end_station_id %in% c("DIVVY 001", "DIVVY 001 - Warehouse test station", "Hubbard Bike-checking (LBS-WH-TEST)", "Pawel Bialowas - Test- PBSC charging station", "DIVVY CASSETTE REPAIR MOBILE STATION", "2059 Hastings Warehouse Station", "Hastings WH 2", "Throop/Hastings Mobile Station")) %>% 
  count(end_station_id)
colSums(is.na(all_trips_v3))

```
```{r}
### Check the data

summary(all_trips_v3)

```
```{r}
### Check percentage of the customer usage

all_trips_v3 %>% 
  group_by(member_casual) %>% 
  summarise(count = n(), Percentage = n()/nrow(all_trips_v3)*100)

```
```{r}
### Make a visualization

ggplot(all_trips_v3, aes(member_casual, fill = member_casual)) +
  geom_bar() +
  labs(x = "User Type", y = "Count", title = "Total Rides by User Type: Casual vs Member") +
   annotate("text",x=1,y=2000000,label="2,295,882 / (41%)",color="black",size=3.5) +
   annotate("text",x=2,y=3000000,label="3,325,265 / (59%)",color="black",size=3.5)
```
```{r}
### Visualizing total rides by customer type

all_trips_v3 %>% 
  group_by(member_casual, rideable_type) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x = member_casual, y = count, fill = rideable_type)) +
  geom_bar(stat = "identity", width = 0.3)
  labs(x="Bike Type", y="Number of Rides", title = "Total Rides by user type and bike type")


```
```{r}
### Average ride length by the customer in minutes

summary(all_trips_v3$ride_length)
aggregate(all_trips_v3$ride_length_min~all_trips_v3$member_casual,FUN=mean)
```
```{r}
### Summarize data by ride length

all_trips_v3 %>%
  group_by(member_casual) %>%
  summarize(`<= 5min` = sum(ride_length_min <= 5),
            `<= 12min` = sum(ride_length_min <= 12),
            `<= 20min` = sum(ride_length_min <= 20),
            `<= 45min` = sum(ride_length_min <= 45),
            `<= 60min` = sum(ride_length_min <= 60),
            `> 2hrs` = sum(ride_length_min > 120),
            `> 4hrs` = sum(ride_length_min > 240),
            `> 6hrs` = sum(ride_length_min > 360)) %>%
  add_row(member_casual = "Total",
          `<= 5min` = sum(.$`<= 5min`),
          `<= 12min` = sum(.$`<= 12min`),
          `<= 20min` = sum(.$`<= 20min`),
          `<= 45min` = sum(.$`<= 45min`),
          `<= 60min` = sum(.$`<= 60min`),
          `> 2hrs` = sum(.$`> 2hrs`),
          `> 4hrs` = sum(.$`> 4hrs`),
          `> 6hrs` = sum(.$`> 6hrs`))
```
```{r}
### More members use it for 30 minutes or less

all_trips_v3 %>% 
   group_by(member_casual) %>% 
  summarize("<12 min" = sum(ride_length_min < 11.99),
            "12-20 min" = sum(ride_length_min >= 12 & ride_length_min <= 20.99),
            "21-30 min" = sum(ride_length_min >= 21 & ride_length_min <= 30.99),
            "31-60 min" = sum(ride_length_min >= 31 & ride_length_min <= 60),
            "61-120 min" = sum(ride_length_min >= 60.01 & ride_length_min <= 120.99),
            "121-240 min" = sum(ride_length_min >= 121 & ride_length_min <= 240.99),
            "241+min" = sum(ride_length_min >= 241))  

```
```{r}
### Add a new column to view ride length

all_trips_v3 <- all_trips_v3 %>% mutate(ride_length_cat = case_when(
                        ride_length_min < 11.99 ~ "< 12 min",
                        ride_length_min >= 12 & ride_length_min <= 20.99 ~ "12-20 min",
                        ride_length_min >= 21 & ride_length_min <= 30.99  ~ "21-30 min",
                        ride_length_min >= 31 & ride_length_min <= 60.99  ~ "31-60 min",
                        ride_length_min >= 60 & ride_length_min <= 120.99  ~ "61-120 min",
                        ride_length_min >= 121 & ride_length_min <= 240.99  ~ "121-240 min",
                        ride_length_min >= 241  ~ "241+ min"))

```
```{r}
### Visualize data by total rides and customer type

all_trips_v3 %>% 
  group_by(member_casual, ride_length_cat) %>% 
  summarise(count = n()) %>%
  ggplot(aes(x=factor(ride_length_cat, level = c("< 12 min", "12-20 min", "21-30 min", "31-60 min","61-120 min", "121-240 min", "241+ min")), y = count, fill = member_casual)) + 
  geom_col(position = "dodge") +
  labs(x="Ride Length Category", y="Number of Rides", title = "Total Rides by user type and ride length category")

```
```{r}
### Average Ride length in minutes

all_trips_v3 %>% filter(ride_length_cat == "< 12 min") %>% 
  group_by(member_casual) %>% 
  summarize(avg_ride_length=mean(ride_length_min))
```
```{r}
### riders with <=20 minutes

all_trips_v3 %>% filter(ride_length_cat == "< 12 min" | ride_length_cat== "12-20 min") %>% 
  group_by(member_casual) %>% 
  summarize(avg_ride_length=mean(ride_length_min))
```
```{r}
### Visualize average ride length in minutes by customer type

all_trips_v3 %>% 
  group_by(member_casual, hour) %>% 
  summarise(count = n(), average_ride_length=mean(ride_length_min)) %>% 
  arrange(member_casual, hour) %>% 
  ggplot(aes(x=factor(hour, level= c(6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4,5)), y=average_ride_length, fill=member_casual)) + 
  geom_col(position = "dodge") +
  labs(x="Hour of day", y="Ride Length (in minutes)", title = "Average ride length by user type and hour of day")

### Caual customers average longer rides than member riders
```
```{r}
### Average ride length of each trip by customer type in the time of day

axis_labels <- c("Early Morning \n6am-9am", "Mid Morning \n9am-12pm", "Afternoon \n12pm-6pm", "Evening \n6pm-11pm", "Early Night \n11pm-3am", "Wee Night \n3am-6am")

all_trips_v3 %>% 
  group_by(member_casual, time_of_day) %>% 
  summarise(count = n(), average_ride_length=mean(ride_length_min)) %>% 
  ggplot(aes(x=factor(time_of_day, level= c("Early Morning", "Mid Morning", "Afternoon", "Evening", "Early Night", "Late Night")), y=average_ride_length, fill=member_casual)) + 
  geom_col(position = "dodge", width = 0.4) +
  labs(x="Time of Day", y="Ride Length (in minutes)", title = "Average ride length by user type and time of day") +
  scale_x_discrete(labels = axis_labels)

### Casual customers are more active midmorning and afternoon
### Members are about the same throughout the day
```
```{r}
### Average ride length of each trip

aggregate(all_trips_v3$ride_length_min ~all_trips_v3$member_casual + all_trips_v3$day_of_week, FUN = mean)
### Both members and casual customers use it more on the weekends but casual use them a lot more time than members
```
```{r}
all_trips_v3 %>% 
  group_by(member_casual, day_of_week) %>% 
  summarise(count = n(), average_ride_length=mean(ride_length_min)) %>% 
  ggplot(aes(x=factor(day_of_week, level= c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")), y=average_ride_length, fill=member_casual)) + 
  geom_col(position = "dodge", width = 0.4) + 
  labs(x="Day of Week", y="Ride Length (in minutes)", title = "Average ride length by user type and day of the week")
```
```{r}
### Members peek two times from 6 am to 8 am and again 4 pm to 6 pm
### Casual customers peak from 3 pm to 6 pm

all_trips_v3 %>% 
  group_by(member_casual, hour) %>% 
  summarise(count = n()) %>%  
  arrange(member_casual, hour) %>% 
  ggplot(aes(x=factor(hour, level= c(6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4,5)), y=count, fill=member_casual)) + 
  geom_col(position = "dodge") +
  labs(x="Hour of day", y="Number of Rides", title = "Total Rides by user type and hour of day")
  
```
```{r}
### Members are more active throughout the day and casual are more active in the early night

all_trips_v3 %>% 
   group_by(member_casual) %>% 
  summarize("Early Morning" = sum(time_of_day == "Early Morning"),
            "Mid Morning" = sum(time_of_day == "Mid Morning"),
            "Afternoon" = sum(time_of_day == "Afternoon"),
            "Evening" = sum(time_of_day == "Evening"),
            "Early Night" = sum(time_of_day == "Early Night"),
            "Late Night" = sum(time_of_day == "Late Night"))
```
```{r}
### Visualize total rides by user type
### Members are active in the morning and both members and casual customers peak in the afternoon-evening

all_trips_v3 %>% 
  group_by(member_casual, time_of_day) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x=factor(time_of_day, level= c("Early Morning", "Mid Morning", "Afternoon", "Evening", "Early Night", "Late Night")), y=count, fill=member_casual)) + 
  geom_col(position = "dodge", width = 0.4) + 
  labs(x="Time of Day", y="Number of Rides", title = "Total Rides by user type and time of day") +
  scale_x_discrete(labels = axis_labels)
```
```{r}
### Visualization for total rides by user

all_trips_v3 %>% 
  group_by(member_casual, time_of_day) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x=factor(time_of_day, level= c("Early Morning", "Mid Morning", "Afternoon", "Evening", "Early Night", "Late Night")), y=count, color=member_casual)) + 
  geom_point() + geom_line(aes(group = member_casual)) +
  labs(x="Time of Day", y="Number of Rides", title = "Total Rides by user type and time of day") + ylim(0, NA) +
  scale_x_discrete(labels = axis_labels)
```
```{r}
### Rides by customer type and day of the week

all_trips_v3 %>% 
   group_by(member_casual) %>% 
  summarize("Monday" = sum(day_of_week == "Monday"),
            "Tuesday" = sum(day_of_week == "Tuesday"),
            "Wednesday" = sum(day_of_week == "Wednesday"),
            "Thursday" = sum(day_of_week == "Thursday"),
            "Friday" = sum(day_of_week == "Friday"),
            "Saturday" = sum(day_of_week == "Saturday"),
            "Sunday" = sum(day_of_week == "Sunday"))
```
```{r}
all_trips_v3 %>% 
  group_by(member_casual, day_of_week) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x=factor(day_of_week, level= c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")), y=count, fill=member_casual)) + 
  geom_col(position = "dodge", width = 0.4) + 
  labs(x="Day of Week", y="Number of Rides", title = "Total Rides by user type and day of the week")
```
```{r}
### Total rides by the user and day of the week
### Members use the service during the week and less on the weekend
### Casual customers are more active during the weekend and less during the week

all_trips_v3 %>% 
  group_by(member_casual, day_of_week) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x=factor(day_of_week, level= c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")), y=count, color=member_casual)) + 
  geom_point() + geom_line(aes(group = member_casual)) + 
  labs(x="Day of Week", y="Number of Rides", title = "Total Rides by user type and day of the week") +
   ylim(0, NA)

```
```{r}
### Total rides by customer type and season
### Members are more active throughout the year and casual customers during summer and fall

all_trips_v3 %>% 
  group_by(member_casual, season) %>% 
  summarise(count = n()) %>% 
  ggplot(aes(x=factor(season, level= c("Spring", "Summer", "Fall", "Winter")), y=count, fill=member_casual)) + 
  geom_col(position = "dodge", width = 0.4) + 
  labs(x="Season of Year", y="Number of Rides", title = "Total Rides by user type and season of the year")

```
```{r}
### Top 5 starting stations for casual riders

all_trips_v3 %>% 
  filter(!(is.na(start_station_name))) %>% 
  filter(member_casual == "casual") %>% 
  group_by(start_station_name) %>% 
  summarize(count=n()) %>% 
  arrange(-count) %>% 
  top_n(5)
```
```{r}
### Most casual riders use the Streeter Dr location

all_trips_v3 %>% 
  filter(!(is.na(start_station_name))) %>% 
  filter(member_casual == "casual") %>% 
  group_by(start_station_name) %>% 
  summarize(count=n()) %>% 
  arrange(-count) %>% 
  top_n(5) %>% 
  mutate(start_station_name= fct_reorder(start_station_name, count)) %>% 
  ggplot(aes(x=start_station_name, y=count, fill=count)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x="Number of Rides", y="Start Station Name", title="Top 5 starting stations for casual riders")
```
```{r}
###  The Streeter Dr location is also the top end_station_name

all_trips_v3 %>% 
  filter(!(is.na(end_station_name))) %>% 
  filter(member_casual == "casual") %>% 
  group_by(end_station_name) %>% 
  summarize(count=n()) %>% 
  arrange(-count) %>% 
  top_n(5)
```
```{r}
### Top starting stations for member riders

all_trips_v3 %>% 
  filter(!(is.na(start_station_name))) %>% 
  filter(member_casual == "member") %>% 
  group_by(start_station_name) %>% 
  summarize(count=n()) %>% 
  arrange(-count) %>% 
  top_n(5)
```
```{r}
### The top start station for members is the Kingsbury St location

all_trips_v3%>% 
  filter(!(is.na(start_station_name))) %>% 
  filter(member_casual== "member") %>% 
  group_by(start_station_name) %>% 
  summarize(count=n()) %>% 
  arrange(-count) %>% 
  top_n(5) %>% 
  mutate(start_station_name= fct_reorder(start_station_name, count)) %>% 
  ggplot(aes(x=start_station_name, y=count, fill=count)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x="Number of Rides", y="Start Station Name", title="Top 5 starting stations for member riders")
```
```{r}
### The Kingsbury st location is the top end_station_name for members
all_trips_v3 %>% 
  filter(!(is.na(end_station_name))) %>% 
  filter(member_casual == "member") %>% 
  group_by(end_station_name) %>% 
  summarize(count=n()) %>% 
  arrange(-count) %>% 
  top_n(5) %>% 
  mutate(end_station_name= fct_reorder(end_station_name, count)) %>% 
  ggplot(aes(x=end_station_name, y=count, fill=count)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(x="Number of Rides", y="Start Station Name", title="Top 5 starting stations for member riders")
```
```{r}
write_csv(all_trips_v3,file = "all_trips_v3.csv")
```


